name: Publish Packages to npm

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      # Optional: Run tests
      - name: Run tests
        run: bun test
      # Publish to npm
      - name: Publish to npm
        run: bun publish --ignore-scripts --access public
        env:
          HUSKY: 0
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
